name: Deploy Hexo Blog             # GitHub Actions 的名称，可自行命名

# 当 push 事件发生时触发部署
on:
  push:
    branches:
      - main                       # 当推送到 main 分支时触发部署（根据你的分支选择）

jobs:
  deploy:
    runs-on: ubuntu-latest          # 运行环境选择最新的 Ubuntu

    steps:
    # 步骤 1：拉取代码
    - name: Checkout repository     # 从 GitHub 仓库拉取代码
      uses: actions/checkout@v2
      with:
        ref: main                   # 拉取 main 分支代码

    # 步骤 2：设置 Node 环境
    - name: Setup Node.js           # 安装 Node.js 环境
      uses: actions/setup-node@v2
      with:
        node-version: 'v22'           # 设置 Node.js 版本

    # 步骤 3：安装依赖
    - name: Install dependencies    # 安装 Hexo 和相关依赖
      run: |
        npm install -g hexo-cli     # 安装 Hexo 命令行工具
        npm install                 # 安装项目依赖

    # 步骤 4：生成静态文件
    - name: Hexo Generate            # 使用 Hexo 生成静态文件
      run: |
        hexo clean                  # 清理旧的生成文件
        hexo generate               # 生成新的静态文件
    - name: Deploy to EdgeOne Pages
      run: npx edgeone pages deploy public -n default-pages-zone -t ${{ secrets.EDGEONE_TOKEN }}
      env:
        EDGEONE_TOKEN: ${{ secrets.EDGEONE_TOKEN }}