name: Build and Deploy to EdgeOne

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 进入子目录并构建
      - name: Build VitePress Site
        run: |
          npm install
          npm run build
      
      - name: List Files
        run: |
          ls -lh ./public
      # 部署时指定相对于仓库根目录的完整路径
      - name: Deploy to EdgeOne Pages
        uses: TencentEdgeOne/edgeone-pages-action@v1
        with:
          token: ${{ secrets.EDGEONE_API_TOKEN }}
          project-name: "lemonblog"
          build-path: "./public"  # 👈 关键：从根目录开始的路径